# Numpy: Numeric computing library

In [1]:
import sys
import numpy as np

### Basic Numpy Arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a=np.array([1,2,3,4])

In [4]:
b=np.array([0,.5,1,1.5,2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Array Types

In [13]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
b.dtype

dtype('float64')

In [23]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [24]:
c = np.array(['a', 'b', 'c'])

In [25]:
c.dtype

dtype('<U1')

In [28]:
d = np.array([{'a' : 1}, sys])

In [29]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Dimensions and shapes

In [31]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [32]:
A.shape

(2, 3)

In [33]:
A.ndim

2

In [34]:
A.size

6

In [35]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [36]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [37]:
B.shape

(2, 2, 3)

In [38]:
B.ndim

3

In [40]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [41]:
C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
]) # Los arrays deben ser consistentes en sus dimensiones

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Indexing and Slicing of Matrices

In [42]:
# Square matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [43]:
A[1]

array([4, 5, 6])

In [44]:
A[1][0]

4

In [45]:
A[1,0]

4

In [56]:
A[0:2]

array([[ 1,  2,  3],
       [10, 10, 10]])

In [57]:
A[:, :2] # Selecciona todas las filas pero de la columna 0 hasta la 2 (no incluida)

array([[ 1,  2],
       [10, 10],
       [99, 99]])

In [58]:
A[:2, :2] # Selecciona las filas y columndas desde la 0 hasta la 2 (sin incluir)

array([[ 1,  2],
       [10, 10]])

In [62]:
A[:2, 2:] # Hasta la fila 2 (no incluida) y a partir del elemento 2

array([[ 3],
       [10]])

In [50]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
A[1] = np.array([10, 10, 10])

In [54]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [51]:
A[2]=99

In [52]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Summary statistics

In [63]:
a = np.array([1,2,3,4])

In [64]:
a.sum()

10

In [65]:
a.mean() # Media aritmética

2.5

In [67]:
a.std() # Desviación estándar (cuánto se alejan en promedio los datos respecto a la media)

1.118033988749895

In [68]:
a.var() # Varianza (cuánto se dispersan los valores en cuanto a la media)

1.25

In [69]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [70]:
A.sum()

45

In [71]:
A.mean()

5.0

In [72]:
A.std()

2.581988897471611

In [74]:
A.sum(axis=0)

array([12, 15, 18])

In [76]:
A.sum(axis=1)

array([ 6, 15, 24])

In [77]:
A.mean(axis=0)

array([4., 5., 6.])

In [78]:
A.mean(axis=1)

array([2., 5., 8.])

In [79]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [80]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Broadcasting and Vectorized operations

In [81]:
a = np.arange(4)

In [82]:
a

array([0, 1, 2, 3])

In [95]:
a + 10

array([10, 11, 12, 13])

In [96]:
a * 10

array([ 0, 10, 20, 30])

In [85]:
a

array([0, 1, 2, 3])

In [97]:
a += 100

In [87]:
a

array([100, 101, 102, 103])

In [88]:
l = [0,1,2,3]

In [89]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [90]:
a = np.arange(4)

In [91]:
a

array([0, 1, 2, 3])

In [92]:
b = np.array([10,10,10,10])

In [98]:
a + b

array([110, 111, 112, 113])

In [99]:
a * b

array([1000, 1010, 1020, 1030])