## Ejercicios Día 1 - NumPy

- Array de 10 ceros → cambia el 5º valor a 1
- Array del 0 al 9 → invierte
- Matriz 3x3 con valores del 0 al 8
- Matriz identidad 4x4
- Array de 10 números aleatorios entre 0 y 1
- Multiplicación elemento a elemento de dos arrays
- Media, std, suma de array con 20 aleatorios
- Matriz 5x5 → modificar diagonal principal
- Máscara booleana para valores mayores a la media
- .reshape() array 1D a 3x3
- .mean(axis=1) y .std(axis=0) en matriz aleatoria

In [1]:
import sys
import numpy as np

In [34]:
# EJERCICIO 1

In [51]:
zero = np.zeros(10, dtype=int)

In [52]:
zero[4]=1

In [53]:
zero

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [38]:
# EJERCICIO 2

In [47]:
inverso = np.arange(10)

In [48]:
inverso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
inverso[-1::-1] # a[inicio:fin:paso]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
a = np.arange(10)[::-1]
print(a) # ESTA ES OTRA FORMA

[9 8 7 6 5 4 3 2 1 0]


In [42]:
# EJERCICIO 3

In [43]:
A = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])

In [44]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
matriz = np.arange(9).reshape(3, 3)
print(matriz) # ESTA ES OTRA FORMA

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
# EJERCICIO 4

In [54]:
identidad = np.eye(4)

In [55]:
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
# EJERCICIO 5

In [74]:
aleatorios = np.random.randint(0, 2, size=10)

In [75]:
aleatorios

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1])

In [76]:
# EJERCICIO 6

In [78]:
a = np.array([1,2,3])
b = np.array([4,5,6])

producto = a * b

In [79]:
producto

array([ 4, 10, 18])

In [85]:
# EJERCICIO 7

In [81]:
arr = np.random.rand(20)

media=arr.mean()
std=arr.std()
suma=arr.sum()

In [82]:
media

0.45510446048467096

In [83]:
std

0.3043716753979581

In [84]:
suma

9.10208920969342

In [86]:
# EJERCICIO 8

In [87]:
m = np.random.randint(0,10,(5,5))
np.fill_diagonal(m,99)

In [88]:
m

array([[99,  5,  2,  4,  4],
       [ 0, 99,  3,  5,  5],
       [ 9,  4, 99,  1,  7],
       [ 4,  5,  1, 99,  2],
       [ 1,  4,  5,  4, 99]])

In [89]:
# EJERCICIO 9

In [90]:
arr = np.random.randint(0, 100, 10)
mascara = arr > arr.mean()

In [91]:
arr

array([20, 73, 73, 86, 13, 91, 69,  8, 19, 88])

In [92]:
arr.mean()

54.0

In [93]:
mascara

array([False,  True,  True,  True, False,  True,  True, False, False,
        True])

In [94]:
arr[mascara]

array([73, 73, 86, 91, 69, 88])

In [95]:
# EJERCICIO 10

In [96]:
a = np.arange(9)
a_reshaped = a.reshape(3,3)

In [98]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
a_reshaped

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
# EJERCICIO 11

In [ ]:
mat = np.random.rand(4,3)

media_filas = mat.mean(axis=1)
std_columnas = 