# Numpy: Numeric computing library

In [1]:
import sys
import numpy as np

### Boolean arrays
_(Also called masks)_

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [5]:
a[0], a[-1]

(0, 3)

In [4]:
a[[0, -1]]

array([0, 3])

In [7]:
a[[True, False, False, True]] # Con True or False indicas los elementos que quieres seleccionar

array([0, 3])

In [8]:
a >= 2

array([False, False,  True,  True])

In [9]:
a[a >= 2]

array([2, 3])

In [10]:
a.mean()

1.5

In [11]:
a[a > a.mean()]

array([2, 3])

In [15]:
a[~(a > a.mean())] # Esto muestra los valores que no son superiores a mean, es decir lo contrario al statement

array([0, 1])

In [16]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [17]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [19]:
A = np.random.randint(100, size=(3,3))

In [20]:
A

array([[50, 82,  7],
       [97, 10, 68],
       [83, 12, 50]])

In [21]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([50,  7, 10, 83, 50])

In [22]:
A>30

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False,  True]])

In [23]:
A[A>30]

array([50, 82, 97, 68, 83, 50])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Linear Algebra

In [24]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])    

In [25]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [26]:
A.dot(B) # Producto matricial (Operación que suma los productos cruzados de las filas de la primera matriz A con las columnas de las segunda matriz B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [32]:
A @ B #  Lo mismo pero más moderno

array([[20, 14],
       [56, 41],
       [92, 68]])

In [33]:
B.T # Traspuesta de una matriz (Matriz que se obtiene intercambiando filas por columnas)

array([[6, 4, 2],
       [5, 3, 1]])

In [30]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Useful Numpy functions

### `random` 

In [48]:
np.random.random(size=2) # Genera un array de 2 números aleatorios decimales entre 0.0 y 1.0 (distribución uniforme)

array([0.7392548 , 0.97659418])

In [49]:
np.random.normal(size=2) # Genera un array de 2 números aleatorios con distribución normal (gaussiana), es decir, con forma de campana

array([-1.63413737, -1.47341528])

In [50]:
np.random.rand(2,4) # Genera una matriz de 2 filas y 4 columnas con números aleatorios decimales entre 0.0 y 1.0 (distribución uniforme)

array([[0.51035792, 0.08111512, 0.65514445, 0.73077899],
       [0.37888326, 0.65109952, 0.41479973, 0.36607392]])

---
### `arange` 

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [54]:
np.arange(0, 1, .1) # Inicio-Fin-Paso

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [56]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [61]:
np.linspace(0, 1, 5) # Genera un array de 5 valores equispaciados entre 0 y 1, ambos incluidos.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [63]:
np.linspace(0,1,20,False) # No incluye el 1, por lo que genera 20 valores equispaciados hasta justo antes del 1

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.zeros((3,3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [68]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.empty(5) # Genera un array de 5 elementos sin inicializar, es decir, con valores basura aleatorios que ya están en la memoria.

array([1., 1., 1., 1., 1.])

In [74]:
np.empty((2,2)) # Crea una matriz de 2x2 sin inicializar, es decir, con valores basura

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [75]:
np.identity(3) # Crea una matriz identidad de 3x3, es decir, una matriz cuadrada con 1 en la diagonal principal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.eye(3,3) # Es similar a la anterior pero siendo más flexible

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
np.eye(8,4,k=1) # Desplaza la diagonal principal una posición por encima de la diagonal principal

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.eye(8,4,k=-3) # Desplaza los 1, tres posiciones por debajo de la diagonal principal

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## EJERCICIO 1:
- Crea una matriz con valores del 0 al 35 y conviértela en una 6x6
- Calcula:
- - np.sum(array, axis=0) Suma por columnas
- - np-sum(array, axis=1) Suma por filas

In [86]:
A = np.arange(36).reshape(6,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [88]:
np.sum(A, axis=0)

array([ 90,  96, 102, 108, 114, 120])

In [89]:
np.sum(A, axis=1)

array([ 15,  51,  87, 123, 159, 195])

---
## EJERCICIO 2:
- Genera una matriz 4x4 con valores aleatorios entre 1 y 100
- Calcula la media
- Cuenta cuántos valores son mayores que la media

In [91]:
A = np.random.randint(1, 101, size=(4,4))
print(A)

[[59 49 95 56]
 [57 87 52 29]
 [90 20 68  7]
 [19 38 93 18]]


In [92]:
A.mean()

52.3125

In [93]:
A[A > A.mean()]

array([59, 95, 56, 57, 87, 90, 68, 93])

---
## EJERCICIO 3:
- Crea una matriz identidad 5x5
- Cambia todos los valores de la diagona principal a 7

In [94]:
A = np.identity(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [95]:
np.fill_diagonal(A, 7)
print(A)

[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]
